language: python
sudo: false
python:
  - "2.7"
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - sudo add-apt-repository ppa:pitti/systemd -y
  - sudo apt-get -qq update
  - sudo apt-get -y install systemd libsystemd-{journal,daemon,login,id128}-dev pkg-config
  - ./bootstrap.sh
install:
  - bin/buildout -N
script:
  - bin/py.test openprocurement/bridge/contracting/tests/ --cov=openprocurement/bridge/contracting
