language: python
sudo: false
python:
  - "2.7"
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - pip install -r requirements.txt
install:
  - bin/buildout -N
script:
  - bin/py.test openprocurement/bridge/contracting/tests/ --cov=openprocurement/bridge/contracting
